"""Runs the full demo pipeline end-to-end against a live GCP project,
following a Bronze -> Silver -> Gold layout:

  1. Bronze  - load every row of demo/data/sample_orders.parquet (~1000
     records, generated by demo/data/generate_sample_orders.py) into
     orders_bronze, as-is (all rows ingested, nothing filtered).
  2. Validate - trigger the orders-dq-scan Dataplex Auto DQ scan against
     Bronze and wait for it.
  3. Quarantine - pull the scan's failed rules' actual bad records via
     their failing_rows_query, export them to a Parquet file in GCS, and
     register that file as an entry in Dataplex Universal Catalog /
     Knowledge Catalog.
  4. Silver - build orders_silver: the same Bronze rows, minus anything
     that appeared in a failing_rows_query, with proper types instead of
     all-STRING.
  5. Gold - build orders_gold: an order-count/revenue-by-status rollup
     over Silver (the business-consumable layer; this is also where a
     multi-source consolidation join would live if there were more than
     one Silver table - see the main framework's pipeline/consolidate.py).
  6. Catalog - register Bronze and Gold in the catalog too, alongside the
     quarantine entry from step 3.

This exercises GCS, BigQuery, Dataplex Data Quality, and Data Catalog /
Knowledge Catalog in one pass, against one table - see DEPLOYMENT.md for
the one-time setup this assumes has already run (buckets, tables, scan,
entry group).

Usage:
  python demo/run_demo.py --project=$PROJECT_ID \
    --raw_bucket=$RAW_BUCKET --quarantine_bucket=$QUARANTINE_BUCKET
"""
import argparse
import json
import logging
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from pipeline.loader import load_orders
from pipeline.dataplex_export import (
    run_scan_and_wait,
    get_scan_job_rule_results,
    export_bad_records_to_parquet,
    register_parquet_quarantine_in_catalog,
)
from pipeline.silver import build_silver_table
from pipeline.gold import build_gold_table
from pipeline.dq_reporting import write_metrics_to_bq, register_table_in_catalog

logger = logging.getLogger(__name__)

DATASET = "dq_demo"
BRONZE_TABLE = "orders_bronze"
SILVER_TABLE = "orders_silver"
GOLD_TABLE = "orders_gold"
DATA_SCAN_ID = "orders-dq-scan"
LOCATION = "us-central1"
ENTRY_GROUP = "dq-demo-group"  # entry group / entry IDs allow only letters, numbers, hyphens


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--project", required=True)
    parser.add_argument("--raw_bucket", required=True, help="Bucket holding demo/data/sample_orders.parquet under raw/orders/")
    parser.add_argument("--quarantine_bucket", required=True, help="Bucket to write the bad-records Parquet file to")
    parser.add_argument("--location", default=LOCATION)
    args = parser.parse_args()

    print("\n=== Step 1: Bronze - load every row of sample_orders.parquet into orders_bronze ===")
    load_result = load_orders(args.project, args.raw_bucket, "raw/orders/", DATASET, BRONZE_TABLE)
    print(json.dumps(load_result, indent=2))

    print("\n=== Step 2: validate - run the Dataplex Auto DQ scan against Bronze ===")
    job_id = run_scan_and_wait(args.project, args.location, DATA_SCAN_ID)
    print(f"Scan job finished: {job_id}")

    print("\n=== Step 3: inspect - pull this job's rule results ===")
    rule_results = get_scan_job_rule_results(args.project, args.location, DATA_SCAN_ID, job_id)
    for r in rule_results:
        status = "PASS" if r["failing_row_count"] == 0 else f"FAIL ({r['failing_row_count']} rows)"
        print(f"  [{status}] {r['rule_name']} (column={r['column']}, dimension={r['dimension']})")

    print("\n=== Step 4: quarantine - export the actual bad records to Parquet in GCS ===")
    export_result = export_bad_records_to_parquet(
        args.project, DATASET, job_id, rule_results, args.quarantine_bucket
    )
    print(json.dumps(export_result, indent=2, default=str))
    register_parquet_quarantine_in_catalog(args.project, args.location, ENTRY_GROUP, export_result)

    print("\n=== Step 5: Silver - Bronze minus quarantined rows, properly typed ===")
    silver_result = build_silver_table(args.project, DATASET, rule_results, bronze_table=BRONZE_TABLE, silver_table=SILVER_TABLE)
    print(json.dumps(silver_result, indent=2))

    print("\n=== Step 6: Gold - order count / revenue rollup by status ===")
    gold_result = build_gold_table(args.project, DATASET, silver_table=SILVER_TABLE, gold_table=GOLD_TABLE)
    print(json.dumps(gold_result, indent=2))

    print("\n=== Step 7: catalog - register Bronze and Gold ===")
    write_metrics_to_bq(
        args.project, DATASET, "dq_metrics",
        {
            "dataset": f"{DATASET}.{BRONZE_TABLE}",
            "rows_loaded": load_result["rows_loaded"],
            "rows_quarantined": export_result["total_rows"],
        },
    )
    register_table_in_catalog(
        args.project, args.location, ENTRY_GROUP, "orders-bronze",
        {
            "display_name": "Demo Orders - Bronze (raw, ingested as-is)",
            "linked_resource": f"//bigquery.googleapis.com/projects/{args.project}/datasets/{DATASET}/tables/{BRONZE_TABLE}",
            "rows_loaded": load_result["rows_loaded"],
            "rows_quarantined": export_result["total_rows"],
        },
    )
    register_table_in_catalog(
        args.project, args.location, ENTRY_GROUP, "orders-gold",
        {
            "display_name": "Demo Orders - Gold (order count / revenue by status)",
            "linked_resource": f"//bigquery.googleapis.com/projects/{args.project}/datasets/{DATASET}/tables/{GOLD_TABLE}",
            "built_from_silver_rows": silver_result["row_count"],
        },
    )

    print("\n=== Done ===")
    print(f"Bronze rows loaded:  {load_result['rows_loaded']}")
    print(f"Rows quarantined:    {export_result['total_rows']}")
    print(f"Silver rows (clean): {silver_result['row_count']}")
    print(f"Gold rows (by status): {gold_result['row_count']}")
    if export_result["gcs_uri"]:
        print(f"Bad records Parquet (archival): {export_result['gcs_uri']}")
        print(f"Bad records BigQuery table (browse rows here): {export_result['bigquery_table']}")
    print(f"Check the Dataplex Universal Catalog console for entry group '{ENTRY_GROUP}' to see all entries.")
    print("Tip: the quarantine_orders table is auto-cataloged by BigQuery/Dataplex - open it in the")
    print("console's Preview tab to see the actual failed rows, not just the summary description.")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    main()
